### PR TITLE
SLING-12107 - JCR Repoinit executes operations out of order

### PR DESCRIPTION
**Pull request by jsedding**

### CODE REVIEW

**Comment by anchela** [comment]
@jsedding , i would have appreciated if you had given me (and everyone else invited for the review) just a tiny bit of time to take a look. i planned to review it today.... and now it's already merged.

**Comment by kwin** [comment]
For me repoinit is not an imperative language but rather a descriptive one of a certain state. Compare with https://sling.apache.org/documentation/bundles/repository-initialization.html

> The code (in form of statements) being executed through repoinit ensures that the repository has a certain state. In case the repository cannot be set up as being mandated through the repoinit statements the startup of the repository fails. This may happen in case the existing parent nodes have node type restrictions which don't allow for the new repository state or in general when the existing node/property state is conflicting with the target one.

Therefore the example of first creating and then deleting a group is something which IMHO should no be supported by repoinit. Rather one should allow to set unbound ACLs in the first place (see SLING-12115).

**Comment by jsedding** [comment]
@anchela apologies for rushing this along! I would still appreciate your review/thoughts on this matter. If this is a controversial change, I am also happy to revert the merge.

**Comment by jsedding** [comment]
@kwin I agree in principal with the idea of repoinit being a declarative language.

Unfortunately, repoinit does not seem to have been designed and implemented to be purely declarative. "create group", "set ACL" and "delete group" all evoke the idea of an action, not a state. Your recent change introducing the statement "ensure ACL" is probably rather an exception.

Therefore, I was still surprised to find that repoinit statements were being reordered. IMHO much of the reordering was also left to chance.

The problem that lead me to this change is the goal, to set up ACLs during initial deployment, for a group that is expected to later be sync'ed on demand from an external identity provider (e.g. LDAP).

One possible solution to this problem is setting up ACLs with a principal name that does not (yet) exist (hence SLING-12115). As a workaround for SLING-12115, I devised the example using "create group", followed by "set ACL" and finally "delete group", which fails due to the reordering of statements.

Another possible solution I experimented with is creating the group with the correct value of the property `rep:externalId` set, effectively pre-creating the group that would later be sync'ed. This property can **only** be set when the group is being created. See below:

```
create group fooBar
set properties on authorizable(foobar)
  set rep:externalId to "fooBar;ldap"
end
```

I have not yet managed to reproduce this issue in a unit test, because it requires a the repository to be set up with external authentication support. However, the above example does not work without this fix, and I have had success using it with the fix applied. Declarative or not, I would argue that the above example should succeed, even though they require ordering.

In order for this setup to be independent of ordering, both statements would need to be collapsed into one, like e.g. this:

```
ensure group with properties
  rep:externalId = "fooBar;ldap"
end
```

The implementation would then need to delete and recreate the group if the property `rep:externalId` is missing and it cannot be added without an exception.

**Comment by jsedding** [comment]
**Update:**

Yesterday evening I wrote a unit test around the repoinit snippet below, making sure the repository is initialized with the validator for `rep:externalId`. I'll contribute this test today via a separate PR.

It turns out that I was wrong (my manual tests must have been incorrect) and this snippet works (test passes). I even went back to org.apache.sling.jcr.repoinit-1.1.38 and the  test also passes.

```
create group fooBar
set properties on authorizable(fooBar)
  set rep:externalId to "fooBar;ldap"
end
```

Subsequently, I repeated my manual tests twice and they also passed.

Now the question is whether this change should be reverted? I still consider it a valuable change/fix that better aligns the implementation with implicit expectations of the users of repoinit. WDYT @anchela, @kwin ?

@kwin I saw your comment regarding documentation and will add a paragraph if we decide to keep this change.

**Comment by kwin** [comment]
I don't think this change does any harm and better fulfils the [principle of least surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment). Therefore I won't revert.

**Pull request merged**
