### PR TITLE
SLING-9857: implement forced path with simple recreate

### PR DESCRIPTION
**Pull request by karlpauls**

### CODE REVIEW

**Comment by anchela** [comment]
@karlpauls , as discussed.... i refactored your proposed to
- get rid of the duplications for users/system users/groups
- avoid repeated calls to UserUti.getAuthorizable which always looks up the user/group from scratch and in oak performs a query on the repository (4 times just for the system-user-creation seems just a bit too much).

please review if i didn't miss/break something while refactoring :)

**Review by anchela — CHANGES_REQUESTED** [review]
see comment together with my changes....

note: IMO the original code (prior to SLING-9857) had a bug with the lookup UserUtil.getUser. if a group exists it would return null and then try to create the user, which obviously will fail.
i refactored the corresponding part in all 3 methods to use {{UserManager.getAuthorizable(String id, Class authorizableClass)}}, which will throw AuthorizableTypeException if an user/group exists but doesn't have the expected type. while the net effect will IMO be the same, the unnecessary try-to-create is avoided and the failure will be easier to understand.

also i guess more tests are needed..... i didn't check the coverage but the fact that my refactoring didn't cause any test-failures makes me just a little bit suspicious ;)

**Comment by anchela** [comment]
@karlpauls , added a few more tests for the cases where the authorizable to be created exists but with the wrong type. as discussed the handling for system-users is currently not consistent with user.... in the latter case the existing system user would be replace by the createUser statement. not sure if that's ok or if the (currently failing) test is correct

**Comment by karlpauls** [comment]
@anchela, lgtm - I think you are right, we should fail in that case. It doesn't make much sense to me to have a user override a system user. In that case, I would expect an explicit delete first.

**Review by anchela — APPROVED** [review]
:)

**Pull request merged**
