### PR TITLE
SLING-8766 : AclVisitor.setPrincipalAcl: be more lenient with unsupported principals

### PR DESCRIPTION
**Pull request by anchela**
@rombert i would appreciate if you could review the proposed fix for SLING-8766

### CODE REVIEW

**Comment by rombert** [comment]
Hi @anchela . Thank you for submitting this and a patch for SLING-8778 . I am having troubles with the tests - seems they became really flaky recently. I would like to get them to a more stable status - as they would be blocking a release in the current state.

**Comment by anchela** [comment]
@rombert are you referring to the ITs or to unit tests associated with this patch?

**Comment by rombert** [comment]
@anchela - I mean the ITs

**Comment by anchela** [comment]
@rombert ok.... do you think the flaky ITs are related to my patch? as far as I am concerned they were never working properly, so I didn't pay too much attention to them. either way, let me know if there is an issue with the proposed patch that impacts the ITs

**Comment by anchela** [comment]
@rombert btw i found that @raducotescu  already reported SLING-8740 for the failing ITs.

**Comment by rombert** [comment]
The tests consistently pass for me locally, both before and after your patch. It's very unlikely that this PR causes test failures, so I'll merge it, but make SLING-8740 a prerequisite for the next release.

**Pull request merged**
