### PR TITLE
Sling 8757

### PR DESCRIPTION
**Pull request by anchela**

### CODE REVIEW

**Comment by anchela** [comment]
@bdelacretaz , @rombert may i ask you to merge changes? for some reason i can't...

**Comment by bdelacretaz** [comment]
> ...may i ask you to merge changes? for some reason i can't...

I cannot help right now but the "I can't" bit should be fixed?

User `angela` looks good to me at https://whimsy.apache.org/roster/committee/sling but maybe your Git permissions haven't been updated correctly?

**Comment by rombert** [comment]
@anchela - I think that you need to to set up your account for GitHub 2FA following the instructions at https://sling.apache.org/project-information.html#source-repository

**Comment by anchela** [comment]
@rombert thanks.... done. waiting for the github invitation now.

**Comment by rombert** [comment]
Merging on behalf on Angela, until she completes her Github setup.

**Pull request merged**
