### PR TITLE
SLING-9091 : Principal-based AC-setup fails for transient service users

### PR DESCRIPTION
**Pull request by anchela**

### CODE REVIEW

**Comment by rombert** [comment]
@anchela  - can you please update the pom.xml so that it references the 1.4.1-SNAPSHOT version of `repoinit.parser`? Right now it fails to build on Jenkins

**Comment by bdelacretaz** [comment]
> ...the 1.4.1-SNAPSHOT version of repoinit.parser..

I have just pushed a change to that version for SLING-8757 so that should be good now

**Comment by rombert** [comment]
Thanks @bdelacretaz . I guess @anchela would need to rebase and force-push her commit for the build to work

**Comment by anchela** [comment]
@rombert my change is not depending on a more recent version of the repoinit parser. it fixes an issue with the jcr implementation. why do you think i need to update the dependency?

**Comment by rombert** [comment]
@anchela - the project depends on the version under vote in the pom.xml, so it will fail until that version is released and available on Maven Central.

**Comment by bdelacretaz** [comment]
Merging as is worked fine and the parser snapshot in the pom is good due to my prior changes

**Pull request merged**
